print("Food Delivery Application")

print("1. User Registration")
print("2. User Login")
print("3. Search Restaurants and Food")
print("4. Add Food to Cart")
print("5. Online Payment")
print("6. Track Order")
print("7. View Order History")
print("8. Rate Order")
